=== hoangdvse62687/Anime_Suggestion/Anime_Suggestion/build/web/WEB-INF/source/configs.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://xml.netbeans.org/schema/configs"
           xmlns="http://xml.netbeans.org/schema/configs"
           elementFormDefault="qualified">
           
    <!-- Declare Http String -->
    <xs:simpleType name="link">
        <xs:restriction base="xs:string">
            <xs:pattern value="(http|https)://[a-zA-Z0-9]+.[a-zA-Z]{2,6}"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Declare String required length > 1 char -->
    <xs:simpleType name="string">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Declare list string for  shortenMovieDisplayOrder-->
    <xs:simpleType name="shortenListString">
        <xs:restriction base="string">
            <xs:enumeration value="href"/>
            <xs:enumeration value="img"/>
            <xs:enumeration value="name"/>
            <xs:enumeration value="comment"/>
            <xs:enumeration value="viewed"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Declare list string for detailMovieDisplayOrder-->
    <xs:simpleType name="detailDisplayOrderListString">
        <xs:restriction base="string">
            <xs:enumeration value="episode"/>
            <xs:enumeration value="type"/>
            <xs:enumeration value="year"/>
            <xs:enumeration value="description"/>
            <xs:enumeration value="dump"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Declare Config -->
    <xs:complexType name="config" mixed="true">
        <xs:sequence>
            <xs:element name="uri" type="link" />
            <xs:element name="categoryContext" type="string" />
            <xs:element name="parentElementCategory" type="string"/>
            <xs:element name="parentClassCategory" type="xs:string" minOccurs="0"/>
            <xs:element name="formatPagging" type="string"/>
            <xs:element name="endformatPagging" type="xs:string" minOccurs="0"/>
            <xs:element name="parentElementMovie" type="string"/>
            <xs:element name="parentClassMovie" type="xs:string" minOccurs="0"/>
            <xs:element name="imgElementMovie" type="string"/>
            <xs:element name="imgClassMovie" type="xs:string" minOccurs="0"/>
            <xs:element name="imgTargetMovie" type="string"/>
            <xs:element name= "nameClassMovie" type="xs:string" minOccurs="0"/>
            <xs:element name="nameTargetMovie" type="string"/>
            <xs:element name="commentClassMovie" type="xs:string" minOccurs="0"/>
            <xs:element name="commentTargetMovie" type="xs:string" minOccurs="0"/>
            <xs:element name="viewedClassMovie" type="xs:string" minOccurs="0"/>
            <xs:element name="viewedTargetMovie" type="string"/>
            <xs:element name="shortenMovieDisplayOrder" type="shortenListString" maxOccurs="5"/>
            <xs:element name="episodeClassMovieDetail" type="xs:string" minOccurs="0"/>
            <xs:element name="episodeTargetMovieDetail" type="string"/>
            <xs:element name="episodeContextMovideDetail" type="xs:string" minOccurs="0"/>
            <xs:element name="typeClassMovieDetail" type="xs:string" minOccurs="0"/>
            <xs:element name="typeTargetMovieDetail" type="string"/>
            <xs:element name="yearClassMovieDetail" type="xs:string" minOccurs="0"/>
            <xs:element name="yearTargetMovieDetail" type="string"/>
            <xs:element name="yearContextMovieDetail" type="xs:string" minOccurs="0"/>
            <xs:element name="descriptionClassMovieDetail" type="xs:string" minOccurs="0"/>
            <xs:element name="descriptionTargetMovieDetail" type="string"/>
            <xs:element name="descriptionContextMovieDetail" type="xs:string" minOccurs="0"/>
            <xs:element name="dumplicateClassMovieDetail" type="xs:string" minOccurs="0"/>
            <xs:element name="dumplicateTagetMovideDetail" type="xs:string" minOccurs="0"/>
            <xs:element name="detailMovieDisplayOrder" type="detailDisplayOrderListString" maxOccurs="unbounded"/>
            <xs:element name="topWeekNameCLassParent" type="xs:string" minOccurs="0"/>
            <xs:element name="topWeekValueClassParent" type="xs:string" minOccurs="0"/>
            <xs:element name="topWeekElementName" type="xs:string" minOccurs="0"/>
            <xs:element name="topWeekClassUri" type="string"/>
            <xs:element name="topWeekTargetUri" type="string"/>
            <xs:element name="maximumPageGetInCategory" type="xs:positiveInteger"/>
            <xs:element name="forbiddenLinkCategories" type="string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="topWeekImgClass" type="string"/>
            <xs:element name="topWeekImgClassTarget" type="string"/>
            <xs:element name="topWeekClassName" type="string"/>
            <xs:element name="topWeekNameElement" type="string"/>
            <xs:element name="topWeekCommentClass" type="string"/>
            <xs:element name="topWeekCommentElement" type="string"/>
        </xs:sequence>
    </xs:complexType>
    
    
    <xs:element name="configs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="config" type="config" minOccurs="2" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hoangdvse62687/Anime_Suggestion/Anime_Suggestion/build/web/WEB-INF/source/configs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<configs xmlns="http://xml.netbeans.org/schema/configs"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://xml.netbeans.org/schema/configs configs.xsd">
<!--    <config>
        <uri>http://animetvn.tv</uri>
         Format category 
        <categoryContext>thể loại</categoryContext>
        <parentElementCategory>ul</parentElementCategory>
        <parentClassCategory>dropdown-menu</parentClassCategory>
         Format paging 
        <formatPagging>?page=</formatPagging>
        <endformatPagging></endformatPagging>
         Format Data 
        <parentElementMovie>div</parentElementMovie>
        <parentClassMovie>item film_item </parentClassMovie>
        <imgElementMovie>img</imgElementMovie>
        <imgClassMovie>lazyload thumb img-responsive</imgClassMovie>
        <imgTargetMovie>data-src</imgTargetMovie>
        <nameClassMovie>tooltip_title</nameClassMovie>
        <nameTargetMovie>h3</nameTargetMovie>
        <commentClassMovie></commentClassMovie>
        <commentTargetMovie></commentTargetMovie>
        <viewedClassMovie>viewed</viewedClassMovie>
        <viewedTargetMovie>span</viewedTargetMovie>
        
        <shortenMovieDisplayOrder>href</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>img</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>viewed</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>name</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>comment</shortenMovieDisplayOrder>
        Format Get Detail Data
        <episodeClassMovieDetail>has-color</episodeClassMovieDetail>
        <episodeTargetMovieDetail>li</episodeTargetMovieDetail>
        <episodeContextMovideDetail>Số tập</episodeContextMovideDetail>
        <typeClassMovieDetail>has-color</typeClassMovieDetail>
        <typeTargetMovieDetail>li</typeTargetMovieDetail>
        <yearClassMovieDetail>has-color</yearClassMovieDetail>
        <yearTargetMovieDetail>li</yearTargetMovieDetail>
        <yearContextMovieDetail>Năm phát sóng</yearContextMovieDetail>
        <descriptionClassMovieDetail>content</descriptionClassMovieDetail>
        <descriptionTargetMovieDetail>div</descriptionTargetMovieDetail>
        <descriptionContextMovieDetail></descriptionContextMovieDetail>
        
        <dumplicateClassMovieDetail>has-color</dumplicateClassMovieDetail>
        <dumplicateTagetMovideDetail>li</dumplicateTagetMovideDetail>
        
        <detailMovieDisplayOrder>type</detailMovieDisplayOrder>
        <detailMovieDisplayOrder>episode</detailMovieDisplayOrder>
        <detailMovieDisplayOrder>dump</detailMovieDisplayOrder>
        <detailMovieDisplayOrder>year</detailMovieDisplayOrder>
        <detailMovieDisplayOrder>description</detailMovieDisplayOrder>
        Trend in week format
        <topWeekNameCLassParent>id</topWeekNameCLassParent>
        <topWeekValueClassParent>wrank-week</topWeekValueClassParent>
        <topWeekElementName>div</topWeekElementName>
        <topWeekClassUri>rank-film-list</topWeekClassUri>
        <topWeekTargetUri>ul</topWeekTargetUri>
        
        <maximumPageGetInCategory>4</maximumPageGetInCategory>
         Forbidden link categories 
        <forbiddenLinkCategories>/tui-deo-balo-vi-pc158230.html</forbiddenLinkCategories>
        
        <topWeekImgClass>list-top-movie-item-thumb</topWeekImgClass>
        <topWeekImgClassTarget>style</topWeekImgClassTarget>
        <topWeekClassName>list-top-movie-item-vn</topWeekClassName>
        <topWeekNameElement>span</topWeekNameElement>
        <topWeekCommentClass>list-top-movie-item-view</topWeekCommentClass>
        <topWeekCommentElement>span</topWeekCommentElement>
    </config>-->
    
    
    <config>
        <uri>http://animevsub.tv</uri>
         Format category 
        <categoryContext>THỂ LOẠI</categoryContext>
        <parentElementCategory>ul</parentElementCategory>
        <parentClassCategory>sub-menu</parentClassCategory>
         Format paging 
        <formatPagging>trang-</formatPagging>
        <endformatPagging>.html</endformatPagging>
         Format Data 
        <parentElementMovie>li</parentElementMovie>
        <parentClassMovie>TPostMv</parentClassMovie>
        <imgElementMovie>img</imgElementMovie>
        <imgClassMovie>attachment-thumbnail size-thumbnail wp-post-image</imgClassMovie>
        <imgTargetMovie>src</imgTargetMovie>
        <nameClassMovie>Title</nameClassMovie>
        <nameTargetMovie>h2</nameTargetMovie>
        <commentClassMovie></commentClassMovie>
        <commentTargetMovie></commentTargetMovie>
        <viewedClassMovie>Year</viewedClassMovie>
        <viewedTargetMovie>span</viewedTargetMovie>
        <shortenMovieDisplayOrder>href</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>img</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>name</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>comment</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>viewed</shortenMovieDisplayOrder>
        Get Data Format
        <episodeClassMovieDetail>Time AAIco-access_time</episodeClassMovieDetail>
        <episodeTargetMovieDetail>span</episodeTargetMovieDetail>
        <episodeContextMovideDetail></episodeContextMovideDetail>
        <typeClassMovieDetail>AAIco-adjust</typeClassMovieDetail>
        <typeTargetMovieDetail>li</typeTargetMovieDetail>
        <yearClassMovieDetail>Date AAIco-date_range</yearClassMovieDetail>
        <yearTargetMovieDetail>span</yearTargetMovieDetail>
        <yearContextMovieDetail></yearContextMovieDetail>
        <descriptionClassMovieDetail>Description</descriptionClassMovieDetail>
        <descriptionTargetMovieDetail>div</descriptionTargetMovieDetail>
        <descriptionContextMovieDetail></descriptionContextMovieDetail>
        
        <dumplicateClassMovieDetail>AAIco-adjust</dumplicateClassMovieDetail>
        <dumplicateTagetMovideDetail>li</dumplicateTagetMovideDetail>
        
        <detailMovieDisplayOrder>description</detailMovieDisplayOrder>
        <detailMovieDisplayOrder>episode</detailMovieDisplayOrder>
        <detailMovieDisplayOrder>year</detailMovieDisplayOrder>
        <detailMovieDisplayOrder>dump</detailMovieDisplayOrder>
        <detailMovieDisplayOrder>type</detailMovieDisplayOrder>
        Trend in week format
        <topWeekNameCLassParent>id</topWeekNameCLassParent>
        <topWeekValueClassParent>showTopPhim</topWeekValueClassParent>
        <topWeekElementName>section</topWeekElementName>
        <topWeekClassUri>MovieList</topWeekClassUri>
        <topWeekTargetUri>ul</topWeekTargetUri>
        
        <maximumPageGetInCategory>4</maximumPageGetInCategory>
         Forbidden link categories 
        <forbiddenLinkCategories>/tui-deo-balo-vi-pc158230.html</forbiddenLinkCategories>
        
        <topWeekImgClass>attachment-img-mov-sm size-img-mov-sm wp-post-image</topWeekImgClass>
        <topWeekImgClassTarget>src</topWeekImgClassTarget>
        <topWeekClassName>Title</topWeekClassName>
        <topWeekNameElement>div</topWeekNameElement>
        <topWeekCommentClass>div</topWeekCommentClass>
        <topWeekCommentElement>div</topWeekCommentElement>
    </config>
    
    <config>
        <uri>https://anime47.com</uri>
         Format category 
        <categoryContext>thể loại</categoryContext>
        <parentElementCategory>ul</parentElementCategory>
        <parentClassCategory></parentClassCategory>
         Format paging 
        <formatPagging>/</formatPagging>
        <endformatPagging>.html</endformatPagging>
         Format Data 
        <parentElementMovie>div</parentElementMovie>
        <parentClassMovie>movie-item m-block</parentClassMovie>
        <imgElementMovie>div</imgElementMovie>
        <imgClassMovie>public-film-item-thumb ratio-content</imgClassMovie>
        <imgTargetMovie>style</imgTargetMovie>
        <nameClassMovie>movie-title-1</nameClassMovie>
        <nameTargetMovie>div</nameTargetMovie>
        <commentClassMovie>fbcom-left</commentClassMovie>
        <commentTargetMovie>span</commentTargetMovie>
        <viewedClassMovie>viewed-right</viewedClassMovie>
        <viewedTargetMovie>span</viewedTargetMovie>
        
        <shortenMovieDisplayOrder>href</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>img</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>name</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>comment</shortenMovieDisplayOrder>
        <shortenMovieDisplayOrder>viewed</shortenMovieDisplayOrder>
        Format Get Detail Data
        <episodeClassMovieDetail>movie-dd imdb</episodeClassMovieDetail>
        <episodeTargetMovieDetail>dd</episodeTargetMovieDetail>
        <episodeContextMovideDetail></episodeContextMovideDetail>
        <typeClassMovieDetail>movie-dd dd-cat</typeClassMovieDetail>
        <typeTargetMovieDetail>dd</typeTargetMovieDetail>
        <yearClassMovieDetail>movie-dd</yearClassMovieDetail>
        <yearTargetMovieDetail>dd</yearTargetMovieDetail>
        <yearContextMovieDetail></yearContextMovieDetail>
        <descriptionClassMovieDetail>news-article</descriptionClassMovieDetail>
        <descriptionTargetMovieDetail>div</descriptionTargetMovieDetail>
        <descriptionContextMovieDetail></descriptionContextMovieDetail>
        
        <dumplicateClassMovieDetail>movie-dd</dumplicateClassMovieDetail>
        <dumplicateTagetMovideDetail>dd</dumplicateTagetMovideDetail>
        
        <detailMovieDisplayOrder>episode</detailMovieDisplayOrder>
        <detailMovieDisplayOrder>type</detailMovieDisplayOrder>
        <detailMovieDisplayOrder>dump</detailMovieDisplayOrder>
        <detailMovieDisplayOrder>dump</detailMovieDisplayOrder>
